FROM java

LABEL maintainer "misha"

COPY /project/target/labs-demo-0.0.1-SNAPSHOT.jar /usr/src/myapp/learndocker-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar learndocker-0.0.1-SNAPSHOT.jar